### ISSUE TITLE
Does not collect hot

### ISSUE THREAD

**Issue by Frowen07** [thebrumby/HotWalletClaimer#183] opened 2024-08-18 10:28 UTC
Hi! I saw your wonderful software. Everything is installed and running, but it does not collect Hot. Please help me. Or we can go to telegram and I will pay you if you help me solve the problem. 
My tg is {removed by admin}
![Скриншот 18-08-2024 132725](https://github.com/user-attachments/assets/ffdcf7c0-cfcb-49de-a253-c034fbe9b483)

**Comment by thebrumby** [comment] 2024-08-18 10:31
Do you have Near tokens to pay for the gas fee? The game's historic requirement is > 0.2 Near token per account.

**Comment by Frowen07** [comment] 2024-08-18 10:33
I have free TX

**Comment by Frowen07** [comment] 2024-08-18 10:46
I filled up another 0.5 near, but it still doesn't collect
![Скриншот 18-08-2024 134532](https://github.com/user-attachments/assets/e07ad043-e55a-4e5c-8023-e3a45040c40f)

**Comment by thebrumby** [comment] 2024-08-18 11:25
Hi,

The default action at the end of completing the sign-in screen would be to press enter and add the account to PM2.

I'll message you in Telegram later, or try following the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) to see where the problem is :)

**Comment by thebrumby** [comment] 2024-08-19 09:56
Hi, any update after following the troubleshooting guide?

**Comment by rostamzad1900** [comment] 2024-08-19 19:57
@thebrumby

hey phil
i have a question for you. do you have one wallet on each telegram account or we can create multiple hot wallet on one telegram account ?

until now i have one wallet for each account. but i'm thinking what if i add another wallet to this account. there is any risk??

**Comment by thebrumby** [comment] 2024-08-19 21:09
Hey @rostamzad1900,

I've been running **a lot** of Hot Wallet accounts from a single Telegram account since the project started, and so far, I haven't encountered any significant issues.

While this method of interacting with the games has its drawbacks and limitations, I'm confident that by interacting through the Telegram website and using life-like mouse movements (unlike some bots that magically land on the right element without moving to it or those that just use API calls), we're reducing the risk. However, it’s important to acknowledge that it’s not completely risk-free.

Personally, I use many seed phrases against a single TG account, but everyone needs to decide what level of risk they're comfortable with. Of course, the safest option is simply making the claim on your mobile without using any helper script!

**Comment by rostamzad1900** [comment] 2024-08-19 23:42
Thank you phil @thebrumby 

i record a video of block claiming process with youtube video overlay, it's happen right now in one of my account.
i send this video to your email. check it out. 
don't share it here

**Comment by Frowen07** [comment] 2024-08-20 07:39
@thebrumby does not work. Maybe you will connect via Anydesk and if you fix the software, I will pay you $20, please

**Comment by Jelingam** [comment] 2024-08-21 15:21
> Hey @rostamzad1900,
> 
> I've been running **a lot** of Hot Wallet accounts from a single Telegram account since the project started, and so far, I haven't encountered any significant issues.
> 
> While this method of interacting with the games has its drawbacks and limitations, I'm confident that by interacting through the Telegram website and using life-like mouse movements (unlike some bots that magically land on the right element without moving to it or those that just use API calls), we're reducing the risk. However, it’s important to acknowledge that it’s not completely risk-free.
> 
> Personally, I use many seed phrases against a single TG account, but everyone needs to decide what level of risk they're comfortable with. Of course, the safest option is simply making the claim on your mobile without using any helper script!

you change your username or just logout from existing wallet and create new one ?

**Comment by Jelingam** [comment] 2024-08-21 15:27
> Hey @rostamzad1900,
> 
> I've been running **a lot** of Hot Wallet accounts from a single Telegram account since the project started, and so far, I haven't encountered any significant issues.
> 
> While this method of interacting with the games has its drawbacks and limitations, I'm confident that by interacting through the Telegram website and using life-like mouse movements (unlike some bots that magically land on the right element without moving to it or those that just use API calls), we're reducing the risk. However, it’s important to acknowledge that it’s not completely risk-free.
> 
> Personally, I use many seed phrases against a single TG account, but everyone needs to decide what level of risk they're comfortable with. Of course, the safest option is simply making the claim on your mobile without using any helper script!

you change your username or just logout from existing wallet and create new one ?

i'm logging out from first wallet and change my username but this error keeps repeating and can't be bypassed.

![Screenshot_20240821-182410](https://github.com/user-attachments/assets/9b1ec54b-5176-4e61-bd07-2916f8d7034b)

**Comment by thebrumby** [comment] 2024-08-21 15:41
> i'm logging out from first wallet and change my username but this error keeps repeating and can't be bypassed.

Ah, there has been some confusion regarding your original question. It is possible to claim multiple HOT wallets using a single Telegram account by opening new sessions of the HOT game, selecting the same (saved) Telegram session, and entering a different seed phrase - you can do this indefinitely. However, the HOT developers only allow one seed phrase to be created per Telegram account.

Some users of this script have purchased Telegram accounts (for around $0.99) and obtained seed phrases for Hot and Wave etc. If/when that Telegram account gets locked, you can continue mining from one of your own TG accounts with multiple seed phrases. It doesn't help you get around the issue of one seed phrase per TG username.

**Comment by thebrumby** [comment] 2024-08-21 15:45
> @thebrumby does not work. Maybe you will connect via Anydesk and if you fix the software, I will pay you $20, please

The original poster confirmed they were able to successfully reinstall the software and got everything working again without needing further help :)

**Closed by thebrumby** 2024-08-21 15:45 UTC
