### ISSUE TITLE
Startup auto 

### ISSUE THREAD

**Issue by Wellynounet** [thebrumby/HotWalletClaimer#1] opened 2024-03-25 13:30 UTC
Hello , how to auto start program at startup ?  and dont resetup everything  

thanks again for this good script

**Comment by thebrumby** [comment] 2024-03-25 23:16
Hi, did you use a persistent session tool like SCREEN as described in the instructions? So long as you leave the server on 24/7 there is no need to set it up more than once. 

It could be possible to modify it slightly to save the seed phrase, but I didn't consider this to be secure. Also, Telegram requires QR code or OTP to log in. So overall, it's best to use SCREEN and leave it constantly running in the background :)

**Comment by Wellynounet** [comment] 2024-03-26 06:31
OK i understand why you dont save the seedphrase  for security reason :) 

and you use the selenium driver to connect  in telegram not the APP telegram that why we need everytime to connect with QR code or OTP 

my idea was to launch the telegram app once to go to the HOT accounts to see how much time is left before claim and to relaunch the script once claim is needed to save resources. 

having several sessions on chrome uses up a lot of resources when it would only need to be activated for a few minutes a day :)

**Comment by thebrumby** [comment] 2024-03-26 07:52
Ah, yes I understand now. I experimented with this before and just tried to reconnect later, but I couldn't get it to resume the session, even when trying to set a per-session directory:

chrome_options.add_argument("user-data-dir={}".format(session_path))

Do you have a suggestion on how to overcome this?

**Comment by Wellynounet** [comment] 2024-03-26 08:37
sorry i can't program at all i have ideas but no idea how to implement them or even if it's possible haha

**Comment by thebrumby** [comment] 2024-03-26 08:51
Ah, no worries! From my understanding, the python function used to simulate you interacting with the Nearwallet game (Selenium), isn't really built for pausing and then resuming sessions exactly where they left off, especially without redoing the login process. Obviously, only having to log in once and then leave it running in the background with "screen" is the main benefit, although if the script crashes, or the server reboots, then you lose the benefit. 

It something I'll keep trying to find a way around and with the wonder of GitHub, perhaps someone with a deeper well of experience or a novel approach could suggest a method to conserve resources without compromising the script’s functionality. I truly appreciate your feedback on this issue. I plan to mark this issue as closed later, acknowledging that, while not perfect, the script serves its intended purpose for now. Thank you again for bringing this to our attention!

**Comment by Wellynounet** [comment] 2024-03-31 14:38
hello, I just ask you why is it that after some time with my 3 accounts for claim the Hot I go from 60% CPU usage to 88% when there is nothing else on my server

**Comment by thebrumby** [comment] 2024-03-31 15:06
Hi! I believe the answer might relate to how Google Chrome operates or how your system manages free memory—though it's most likely Chrome.

For each wallet that claims simultaneously, the software creates a separate virtual instance of Google Chrome - on each instance, we log into telegram, and sign into the "game" using the private key. This Browser instance runs continuously, even when the Python script is merely waiting. If you close the Chrome instance, you'll lose your logged-in status with Telegram and the game.

You can check your available memory with the command below. If the free memory is really low, then the operating system might be swapping data in and out of the "cache".

`free -m`

You can also install and use a CPU usage monitor:

```
sudo apt install htop
htop
```
On my 4-core, 8GB virtual VPS, I am running 4 simultaneous wallet claims, which use about 2 GB of memory and about 25% CPU load. Using HTOP, I can see that the 4 "screen" instances each use 0% of the CPU. However, the four separate Google Chrome background processes are responsible for all the CPU usage.

Could you check if you're experiencing something similar?

**Comment by Wellynounet** [comment] 2024-03-31 15:11
i have reboot the server 
that the screen shot 
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/e9d7e041-ade1-4e2d-8a54-eb06ccea3cd7)

and the free -m command 
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/65cc9e4c-4de4-4141-bde9-6cedb31ea060)

i have 6 gigs of ram in my server

**Comment by thebrumby** [comment] 2024-03-31 15:28
Yes, on my own server too, it's the same behavior. The CPU usage primarily stems from Google Chrome instances that are continually waiting for Selenium commands. Or, to put it another way, Google Chrome doesn't know we intend to sit idle for the next few hours, so is constantly running and waiting our commands. However, our Python script, in essence, remains inactive for the majority of the time, utilizing less than 1% of CPU resources. It only becomes active for a short period when initiating a claim, after which it returns to a state of inactivity, leveraging time.sleep() to wait until the next action is necessary.

Selenium, a third-party Python module our script utilizes, is responsible for facilitating interactions with Google Chrome browser sessions. However, Google Chrome operates independently of our script's intentions, maintaining readiness for interaction commands across each instance associated with our separate screen sessions. This continuous state of readiness results in persistent CPU usage.

Google Chrome's architecture is quite bulky, or consumes a lot of resources, because it allows for virtualization of the screen, enabling features like screenshot capture in our script's debugging functions, even in the absence of a GPU or physical monitor.

Some example of what Chrome is doing in the background are:

<img width="299" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/0ab9eec6-ad41-4312-8269-bf8c4526bc69">

<img width="364" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/1856e784-5f57-43bc-a5a8-0901bc90008f">

<img width="392" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/6985aaea-2549-45d9-98e3-1ab4e4bcff44">

<img width="377" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/06e7481b-8fe8-47d9-9ccc-c7948dd604fb">

**Comment by thebrumby** [comment] 2024-03-31 15:53
Perhaps on my days off next week, I will investigate again if there is a reliable way to close and resume the sessions by closing and reopening the driver. If I can make it save the state successfully, then I will update the public code. Right now, the code has three main functions, log into Telegram, log into the game, and handle the claims. Only one the first time does it to the log in Telegram and log into the game, then afterward it just loop the claim function. If I can refine it to save the status and only open Chrome when it needs to make the claim, I will do so.

**Comment by Wellynounet** [comment] 2024-03-31 16:31
no need if it's normal that it increases the processor use it's fine with me it was just to know 

> Perhaps on my days off next week, I will investigate again if there is a reliable way to close and resume the sessions by closing and reopening the driver. If I can make it save the state successfully, then I will update the public code. Right now, the code has three main functions, log into Telegram, log into the game, and handle the claims. Only the first time does it to the log in Telegram and log into the game, then afterward it just loops the claim function. If I can refine it to save the status and only open Chrome when it needs to make the claim, I will do so. But with my initial attempts at this, it never really saved it, and I had to log back in before every claim, which defeated the benefit of an auto-claim script :)

**Comment by thebrumby** [comment] 2024-03-31 18:49
Thank you once again for the feedback, and I hope our discussions help others in understanding the script's functionality. I welcome further comments if you have them, or any future suggestions. Certainly, the two login functions pose the greatest challenge due to the developers trying to stop automated scripts, which is why I previously tried minimizing interactions with these components (to enhance the script's reliability and reduce the chance of errors). Your input, and that of other users, is important as we strive to improve this tool. Thanks, Phil.

**Comment by thebrumby** [comment] 2024-04-02 16:23
I truly appreciate your encouragement and suggestions for enhancing the script. I'm excited to share that significant progress has been made in my local setup. Now, when the Python script is not actively logging in or claiming, it offloads the Chrome Driver. This means that, even with four sessions open, when idle, it's using less than 1% CPU usage and only a few hundred MBs of RAM.

Additionally, if you reboot the machine but keep the session names consistent across each individual session, the script now remains logged into both Telegram and the app without storing your seed phrases. This opens the door for those familiar with tools like PM2 to fully automate the process, reloading the scripts after a reboot. While I don't plan to formally adopt this as the primary method, I intend to update the Read Me documentation to highlight this possibility.

Your feedback has been key in driving this project forward, and tomorrow I will upload the updates, providing there are no errors overnight. Thanks, Phil.

**Comment by Wellynounet** [comment] 2024-04-02 17:23
I tried to do something similar like saving the telegram session cookies to use them on each account.
just by saving the seed phrase
but chat gpt is not very good

it's a bit painful to reset the connection to telegram and the seedphrase each time
I've had 3 power cuts in 2 days and I'm in a very civilized country :)


can't wait to test your changes

welly
________________________________
De : thebrumby ***@***.***>
Envoyé : mardi 2 avril 2024 18:23
À : thebrumby/HotWalletClaimer ***@***.***>
Cc : Wellynounet ***@***.***>; Author ***@***.***>
Objet : Re: [thebrumby/HotWalletClaimer] Startup auto (Issue #1)


I truly appreciate your encouragement and suggestions for enhancing the script. I'm excited to share that significant progress has been made in my local setup. Now, when the Python script is not actively logging in or claiming, it offloads the Chrome Driver. This means that, even with four sessions open, when idle, it's using less than 1% CPU usage and only a few hundred MBs of RAM.

Additionally, if you reboot the machine but keep the session names consistent across each individual session, the script now remains logged into both Telegram and the app without storing your seed phrases. This opens the door for those familiar with tools like PM2 to fully automate the process, reloading the scripts after a reboot. While I don't plan to formally adopt this as the primary method, I intend to update the Read Me documentation to highlight this possibility.

Your feedback has been key in driving this project forward, and tomorrow I will upload the updates, providing there are no errors overnight. Thanks, Phil.

**Comment by thebrumby** [comment] 2024-04-02 20:07
Hey Welly,

I've conducted numerous tests across a variety of virtual servers and the results seem quite promising:

1) You can continue utilizing SCREEN to manage separate sessions, as we've done previously.
2) Once the login process is fully complete (for both Telegram and entering the Seed Phrase), the script will save your progress and close down Chrome, minimizing resource use.
3) As a result, CPU and RAM usage remains low when the script is idle and  simply passing time between claims, rather than the high usage before.
4) Restarting the script with the same session name you previously used should automatically resume where you left off, without needing to log in anew.
5) Initiating the script with "**python3 claim.py mySession**", where "mySession" is your previous session, will bypass the initial setup options and directly proceed to resuming your session.
6) Given the ability to pass the session name as a command line arguement, you could now leverage PM2 or a similar process manager to automatically reload your session in the event of a script crash or server reboot.
7) I'm aiming to keep this project accessible for all users of all levels, so while PM2 usage is beyond the scope of what I want to directly support here, those familiar with it should find integrating it straightforward. Meanwhile, SCREEN remains a user-friendly alternative for those less accustomed to PM2.

I'm eager to hear how this updated approach works out for you. Please let me know how you get on!

Best regards,
Phil.

**Comment by Wellynounet** [comment] 2024-04-02 20:44
hey , brumby


I just downloaded the new script no worries everything works as well as expected without consuming a huge amount of  resources than the previous  ,

big improvement I'm very happy thank you very much :)
However it must come from me I try to connect my 3rd account on the same telegram like the other 2 and I have this problem I have tested 5 times tjr the same I even reinstalled everything script nothing to do my first account and cursed :)

the other accounts have all been connected with the Qr code provided in the session name folder.
like the not working one

maybe it will work tomorow :)

the python3 claim.py session-name work great too auto connect 🙂

thanks again for the amazing job 🙂



________________________________
De : thebrumby ***@***.***>
Envoyé : mardi 2 avril 2024 22:07
À : thebrumby/HotWalletClaimer ***@***.***>
Cc : Wellynounet ***@***.***>; Author ***@***.***>
Objet : Re: [thebrumby/HotWalletClaimer] Startup auto (Issue #1)


Hey Welly,

I've conducted numerous tests across a variety of virtual servers and the results seem quite promising:

  1.  You can continue utilizing SCREEN to manage separate sessions, as we've done previously.
  2.  Once the login process is fully complete (for both Telegram and entering the Seed Phrase), the script will save your progress and close down Chrome, minimizing resource use.
  3.  As a result, CPU and RAM usage remains low when the script is idle and simply passing time between claims, rather than the high usage before.
  4.  Restarting the script with the same session name you previously used should automatically resume where you left off, without needing to log in anew.
  5.  Initiating the script with "python3 claim.py mySession", where "mySession" is your previous session, will bypass the initial setup options and directly proceed to resuming your session.
  6.  Given the ability to pass the session name as a command line arguement, you could now leverage PM2 or a similar process manager to automatically reload your session in the event of a script crash or server reboot.
  7.  I'm aiming to keep this project accessible for all users of all levels, so while PM2 usage is beyond the scope of what I want to directly support here, those familiar with it should find integrating it straightforward. Meanwhile, SCREEN remains a user-friendly alternative for those less accustomed to PM2.

I'm eager to hear how this updated approach works out for you. Please let me know how you get on!

Best regards,
Phil.

**Comment by Wellynounet** [comment] 2024-04-02 20:49
forget about this part :

"the other accounts have all been connected with the Qr code provided in the session name folder.
like the not working one

maybe it will work tomorow :)
"after deleting the folder welly in screenshot and selenium all working great for all my 3 account


________________________________
De : marc hang ***@***.***>
Envoyé : mardi 2 avril 2024 22:44
À : thebrumby/HotWalletClaimer ***@***.***>
Objet : RE: [thebrumby/HotWalletClaimer] Startup auto (Issue #1)

hey , brumby


I just downloaded the new script no worries everything works as well as expected without consuming a huge amount of  resources than the previous  ,

big improvement I'm very happy thank you very much :)
However it must come from me I try to connect my 3rd account on the same telegram like the other 2 and I have this problem I have tested 5 times tjr the same I even reinstalled everything script nothing to do my first account and cursed :)

the other accounts have all been connected with the Qr code provided in the session name folder.
like the not working one

maybe it will work tomorow :)

the python3 claim.py session-name work great too auto connect 🙂

thanks again for the amazing job 🙂



________________________________
De : thebrumby ***@***.***>
Envoyé : mardi 2 avril 2024 22:07
À : thebrumby/HotWalletClaimer ***@***.***>
Cc : Wellynounet ***@***.***>; Author ***@***.***>
Objet : Re: [thebrumby/HotWalletClaimer] Startup auto (Issue #1)


Hey Welly,

I've conducted numerous tests across a variety of virtual servers and the results seem quite promising:

  1.  You can continue utilizing SCREEN to manage separate sessions, as we've done previously.
  2.  Once the login process is fully complete (for both Telegram and entering the Seed Phrase), the script will save your progress and close down Chrome, minimizing resource use.
  3.  As a result, CPU and RAM usage remains low when the script is idle and simply passing time between claims, rather than the high usage before.
  4.  Restarting the script with the same session name you previously used should automatically resume where you left off, without needing to log in anew.
  5.  Initiating the script with "python3 claim.py mySession", where "mySession" is your previous session, will bypass the initial setup options and directly proceed to resuming your session.
  6.  Given the ability to pass the session name as a command line arguement, you could now leverage PM2 or a similar process manager to automatically reload your session in the event of a script crash or server reboot.
  7.  I'm aiming to keep this project accessible for all users of all levels, so while PM2 usage is beyond the scope of what I want to directly support here, those familiar with it should find integrating it straightforward. Meanwhile, SCREEN remains a user-friendly alternative for those less accustomed to PM2.

I'm eager to hear how this updated approach works out for you. Please let me know how you get on!

Best regards,
Phil.

**Comment by thebrumby** [comment] 2024-04-02 20:58
Great to hear all 3 are working. I have 4 different games accounts who all use the script to claim on the one server (me, my wife, and 2 friends). Sometimes I log in with different Telegram accounts, and sometimes all from mine, so I knew that it should be possible. Pleased to hear deleting the old or corrupted folders means it's now working for all 3 simultaneously.

**Comment by thebrumby** [comment] 2024-04-03 20:21
Hey Welly, I said I wouldn't do it, but then found time anyway! I have now added a section on automating through script crashes and server reboots using PM2!

https://github.com/thebrumby/HotWalletClaimer?tab=readme-ov-file#pm2

**Comment by Wellynounet** [comment] 2024-04-04 05:57
Absolutely, I automated everything by following the tutorial.  
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/9ee115e6-3015-4aa4-973e-df2f732a5a4b)


and i use : 
 pm2 logs
 
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/8e1a1115-065c-4d24-88a5-643fc237173c)
 
 to check everything work fines

**Comment by thebrumby** [comment] 2024-04-04 09:42
Awesome, thanks for the detailed feedback. I added "PM2 log" to the list of commands in the readme - I forgot all about that!

**Comment by Wellynounet** [comment] 2024-04-04 21:25
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/b254786e-7206-40b7-8419-a0a74447c26c)


hey , brumby  i get  errors sometimes i dont know  why

**Comment by thebrumby** [comment] 2024-04-05 11:18
Hey brother, 

Yes, indeed that is one of the most common issues. It says linked in the iPhone, but then it's not linked. There is also another issue when it types "/start" to bring up the link, in the HereWalletBot chat window, if something got typed or out of place with that window, then the script can't interact as normal. There will be a slightly refined version today or tomorrow that's now waiting for the pending claim button to stop spinning before it reads the "time to fill", and it has a few tweaks around starting a new session, but ultimately, if it's either of these 2 issues,  then only the user can do it :)

**Comment by thebrumby** [comment] 2024-04-05 22:56
Hey Welly,

If you get chance, can you test version 1.3.5 for me?

1) It should be cleaner in handling cases when a previous session is aborted part-way through.

2) in addition, there is now the option to reset the session in case things get screwed up:
<img width="779" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/10347b39-1a00-41cb-a498-83fd44470b49">

3) There is a new function that takes over most interactions, which should be more standardized & resilient!
<img width="512" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/83c2d8a4-9814-472b-b234-ac736e925664">

4) At the end of the sign-in section there is now the option to park the script for starting with PM2:
<img width="611" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/6e0e39d1-94c3-4ee4-8c37-0c78887f3dd1">

Any feedback on how it works would be appreciated! Thanks in advance, Phil.

**Comment by Wellynounet** [comment] 2024-04-06 06:41
Hi brumby, I've just downloaded the new version. 



everything is fine  , except this error 

![thorium_oVaycRUmc7](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/6e8f1135-ca0e-4842-9e10-319ac439c728)


and  when its starting on pm2
 is not logging  
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/acec9f1c-7cbf-4bf6-bca8-d0112c8ee5db)
 maybe am rate limited too 
but so far so good 

thanks again BrumB

**Comment by thebrumby** [comment] 2024-04-06 10:28
Thanks for the info, looks like it's linked to the ability/inability to find the central box. It might be that the session got detached/logged out and is back at the QR code screen. I'll add some additional information and checks around that. Thanks for the feedback.

**Comment by Wellynounet** [comment] 2024-04-06 11:50
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/b1a1abd2-9b79-4ec7-8217-bcebbd026d03)
 
 
  and too much time to wait

**Comment by thebrumby** [comment] 2024-04-06 12:51
OK cool, thanks Welly. 

- The screenshot method not working if you force to log in again was an oversight on my part! That should be fixed. 
- All the issues around the "lag" of not finding the central box are almost certainly that the account got logged out. It now checks if the QR code (log in) screen is showing again and displays warning messages if it is.
- I added warning about not stopping the script while Chrome Driver is active, this almost always logs us out.
- The last issue, with too much time to wait is caused by lag on the game site. I put in checks for this and correctly explain the script will check back in one hour to see if it needs to claim again or just update the timer.

The code is updated again (still 1.3.5). If you see more issues, please let me know.

**Comment by Wellynounet** [comment] 2024-04-06 12:52
> OK cool, thanks Welly.
> 
> * The screenshot method not working if you force to log in again was an oversight on my part! That should be fixed.
> * All the issues around the "lag" of not finding the central box are almost certainly that the account got logged out. It now checks if the QR code (log in) screen is showing again and displays warning messages if it is.
> * I added warning about not stopping the script while Chrome Driver is active, this almost always logs us out.
> * The last issue, with too much time to wait is caused by lag on the game site. I put in checks for this and correctly explain the script will check back in one hour to see if it needs to claim again or just update the timer.
> 
> The code is updated again (still 1.3.5). If you see more issues, please let me know.
Thanks for fast troubleshooting :)

any idea how to update the scrpt without redoing everything with loging

**Comment by thebrumby** [comment] 2024-04-06 13:03
Hi Welly, 

PM2 doesn't check to see if the file system was updated, so simply saving 'claim.py' in your 'HotWalletBot' folder should affect anything that is running - they will just continue to run on the previous code. 

However: If the script crashes, if you start a new session, or if you stop/start or restart a PM2 session, then the new code will apply.

It's also probable, that if the script reached it's natural endpoint (I mean, it got to the end and is waiting for the next claim time), then if should restart ok even with the new. code :)

Cheers 🍻 

- 

-

**Comment by Wellynounet** [comment] 2024-04-06 13:51
Thanks all working great and fast != 
no more issues

**Comment by thebrumby** [comment] 2024-04-06 13:54
Good to hear, let's hope they don't change anything in the game mechanics now, and it will keep "mining" for many months to come :)

**Comment by Wellynounet** [comment] 2024-04-07 14:47
hello BrumB

,  hope you have a nice sunday :) 


here  the error  i encountered frequently  when he restart the session 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/880e454f-7a91-44f1-a1b7-94261d1f687a)

**Comment by thebrumby** [comment] 2024-04-08 01:36
Hey Welly, you're getting logged out for some reason which is causing the issue. 

I'll add some error checking for that which will prevent the code crash in v1.3.6. 

- I've added a new lock mechanism that will only allow one claim at a time, which might prevent some clashes.
- I've added a beta feature to save a copy of the session to ./backups after seed phrase entry, and try to restore it if the session crashes, it won't help in all cases.

Otherwise it might be linked to the maximum number of linked devices or something, we'll have to see how the new changes go as to whether it helps or not. I'm running 4 session on 1 TG account, and no issues from my side.

**Comment by Wellynounet** [comment] 2024-04-08 06:33
hi brumby , i've updated the script I'm testing if it works still a bit wobbly it must come from too many accounts on the same telegram and I'll divide into groups

**Comment by thebrumby** [comment] 2024-04-08 06:55
Cool, let me know how you get on :)

**Comment by Wellynounet** [comment] 2024-04-08 17:00
Hello Brumby , 

more than 10 h that the script turns I separated in 2 account TLG different and not had problem the problem had to come from the 5 account no problem 6 account it crashes 



we'll see if it survives the night 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/a33fbc33-243d-4483-a750-c090f78dff7b)

**Comment by thebrumby** [comment] 2024-04-08 17:37
Fingers crossed then! Seems this version is pretty stable, although noted about the maximum number of game accounts per Telegram account. There might not be anything I can do to improve that. Lef’s see.

**Comment by Wellynounet** [comment] 2024-04-08 17:47
> Fingers crossed then! Seems this version is pretty stable, although noted about the maximum number of game accounts per Telegram account. There might not be anything I can do to improve that. Lef’s see.

Yes its me on Telegram :)

**Closed** 2024-04-08 19:32 UTC

**Comment by Wellynounet** [comment] 2024-04-09 12:08
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/eac86669-c022-46bd-a6c4-1abd6682e10d)
 
 30 h without restart or bug everything work fine

**Comment by thebrumby** [comment] 2024-04-09 17:26
Thanks Welly, for your help in testing the script. Hopefully now the bugs seem fixed we will have a reliable way of automated claiming for a long time to come!

**Comment by thebrumby** [comment] 2024-04-10 00:45
Hey Welly,

I released v1.3.8 as the devs introduced a few new hurdles to jump through!

**Comment by Wellynounet** [comment] 2024-04-10 05:25
> les to jump through!
i see something about hold wallet i pull new things 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/b7331b3e-5d28-40af-88c1-5dceb88cf0d8)
 no issue for like 50 h :)

**Comment by thebrumby** [comment] 2024-04-13 00:58
Hey Welly, 

I've incorporated your suggestion to reduce the number of console messages, or more precisely, to adjust the verbosity level between 1 and 3. Level 1 displays mainly error messages or minimal details per claim. Level 2 shows the main steps of each claim, but without all the detail. Level 3 provides all the nitty gritty intricate details of every step.

Cheers, BrumB!
